### ISSUE TITLE
Can you make a professional Janggi (korean chess) engine?

### ISSUE THREAD

**Issue by cjssh1002** [maksimKorzh/xiangqi-stockfish#2]

**Comment by maksimKorzh** [comment]
Hi @cjssh1002 
re: Janggi's rules are similar to xiangqi rules
 - apart from cannons moving diagonally if I'm not mistaken?

re: f you are going to do this, please do janggi as well
- I think adding jiangi as variant is possible and should be easilly achieved without dropping performance.
  So adding jiangi variant might be an option, however not the prior. I still need to do lots of things.

re: If you develop a janggi specialized engine, it will be a good insurance for the future.
 - I thought the same about xiangqi... well, it doesn't seem to be so, we'll see

re: "professional" engine:
 - this is the most arguable. If you're a developer and have a look at the source code, you'll understand what I mean.
   But from the perspective of playing strength my version should be at least as strong as Fairy Stockfish.

So let's say I accept this issue and will keep it open, however I don't promise quick results.
Hope you understand.

**Comment by cjssh1002** [comment]
The cannon does not move diagonally... To move and capture, you only need a piece of mine or another opponent piece (mount), and the basic movement route is the same as that of xiangqi. And cannons cannot capture cannons.

Although xiangqi is more internationally famous than janggi, janggi is more valuable in Korea's popularity compared to xiangqi's popularity in China.

Stockfish janggi hasn't been hardcoded yet. Because I have to keep the basic coding for all variants...
For example PST or endgame data, or basic patterns needed for janggi tactics...

First of all, I think you need to understand janggi rules.

Of course I don't leave everything to you, so I can support you if necessary.

**Comment by maksimKorzh** [comment]
@cjssh1002 
Did you have a look at current xianqqi stockfish code base? (movegen.cpp in particular)?
What do you think?

Let's go the following way:
1. I embed alpha-beta search
2. We work on jianggi variant

How about that?
I can ping you when done.

Another note:
What GUI do you use to play jiangqi with fairy stockfish?
I think my CCBridge Arena can be altered to serve as jianggi GUI,
did you have a look at my GUI?
https://www.youtube.com/watch?v=ZEnVvoXBPho

**Comment by cjssh1002** [comment]
Perhaps you can find the code for janggi's rules in the fairy stockfish ccp file.
I used winboard gui.
Can I use it on Windows 10 system?

**Comment by maksimKorzh** [comment]
No, Fairy Stockfish's code won't work because of bitboards. I'm using array based move generator here. I will search for the rules when the alpha-beta routine is done. Anyway only movegen and eval code would be different while all the rest should be the same.

I'm just wondering why do you need other than Fairy Stockfish engine?
Do you want to run engine matches?
Does Fairy Stockfish support winboard protocol natively?

**Comment by cjssh1002** [comment]
The developer of Fairy Stockfish does not support the UCI protocol for Janggi.
Fairy stockfish janggi supports CECP protocol. So I can run janggi using CECP protocol on winboard. Winboard developer have developed a legitimate move to play janggi.
http://www.open-aurec.com/wbforum/viewtopic.php?f=2&t=54747

The reason why you need other engines besides the Fairy Stockfish is simple.

1. The janggi engine only has 1 (fairy stockfish).
-> Since janggi doesn't have a variety of engines, I have no choice but to rely on Fairy Stockfish. Compared to its popularity, there are few janggi game programs in Korea. In most cases, the intensity of play is very weak.

2. Like you said I need an engine match.
-> For analysis and research on various movements, and I need an openingbook.

3. Fairy stockfish is very powerful, but sometimes a lot of bugs and tactical problems with janggi occur occasionally.
-> I know a lot of theoretical tactics for janggi. At first I wanted to apply it to the fairy stockfish, but as you can see, the fairy stockfish developers can't focus solely on janggi because they have to maintain a variety of chess variants. 
So, I want to apply many of my janggi theories to a new engine. So I need a janggi specialized engine.

4. The only GUI that supports janggi is Winboard. So, I always thank the Winboard developer. 
(Also, additional GUI is required for the diversity of users)
I previously requested janggi GUI support from the cute-chess developer, but at this time development is discontinued and is not available due to a lot of bugs.
https://github.com/gaintpd/cutechess/issues

Janggi is a very traditional and popular game in Korea, but I thought it was necessary to try various things because of such a very poor environment.
And I thought this coding research on Janggi could also be helpful for the xiangqi AI you develop.
Xiangqi is a very defensive tactic, chess is a very aggressive tactic, but janggi is a game that balances defense and attack.

**Comment by maksimKorzh** [comment]
@cjssh1002 
A few notes:
1. Fairy Stockfish is developed by a single person - Fabian Fichter, not by a team as far as I'm aware.
2. Fairy Stockfish is not the only jiangqi engine, **H.G. Muller, maintainer of winboard is now working on jiangqi engine**:
    http://talkchess.com/forum3/viewtopic.php?f=7&t=76465
    It should have a very promising evaluation and obviously compatible with winboard.

I clearly understand your requests from the user's perspective,
I had something similar in mind which resulted creating my ccbridge arena - a proof of concept gui to
play games between UCI/UCCI xiangqi engines, but when I got what I currently have I started feeling even
more disappointed then earlier)

Another issue regards to interaction between engine and GUI. I tried uci2wb adapter and it works but it's too
complicated for the end user to setup the engine this is probably the reason why Fabian added native CECP support
to Fairy Stockfish to run natively in winboard. It's possible to reuse that obviously but anyway with my current skills
you can't expect much improvement comared to Fairy Stockfish. The reason for that is that for evaluation I use material
and piece-square tables (to give engine an idea of where to develop it's pieces) only. I don't know for sure, but I guess
that's something similar to what is used in Fairy Stockfish itself. So the "style" of play would be very very similar to
Fairy Stockfish. I just have a faster move generator and potentially might have as good search as Fairy Stockfish uses
(but without threads for now). In order to get "interesting" and "human-like" style of play NNUE is needed. Fabian is going to
make it for various variants for Fairy Stockfish and I'm gonna reuse it then (I'm too dumb to create my own NNUE).

Just tried to share my concerns as a developer.
Btw are you a developer?
Did you ever write a chess engine?
Did you ever think to do so if not?

**Comment by cjssh1002** [comment]
ok i see. I understand you enough.

Currently, the janggi engine is also executable if the GUI supports the UCI protocol. However, the coordinates are different. So you have to solve this problem in GUI development.
https://github.com/ianfab/Fairy-Stockfish/issues/194

Yes, that is correct. Fabian Fichter developed janggi, but someone already developed fairy stockfish before (there wasn't a janggi variant at that time), and now they are developing each other in connection with pychess, etc., so I said "developers".

And I helped develop his(Fabian) janggi engine and made several contributions. And I'm testing the fairy stockfish janggi every day.
And now, as a Korean person in charge, I am participating in the development of winboard janggi engine.
mostly about non-programming.
and I have never written a chess engine.
Koreans are probably new to chess programming. The janggi program produced by Koreans is a form that combines gui and engine, and uses a completely different proprietary protocol. (Monte Carlo Algorism)

Anyway, the important point at the moment is if you are interested in Korean janggi someday and have a willingness to develop it, then please develop it.

**Comment by maksimKorzh** [comment]
Thanks for your questions.
Your request is accepted, however I can't say for sure If I go for implementing jiangqi or not.
If yes - you'll be the first person to know about it)

Without having a decent search in the engine thinking about different variants is pointless and I've just started
developing search: https://www.youtube.com/watch?v=3sLgdJGJGk0

It takes quite a bit of time to bring it to the state somewhat close to Fairy Stockfish)

**Comment by maksimKorzh** [comment]
@cjssh1002 
I just had a look at jiangi rules at wikipedia, well... it's a different game compared to xiangqi and I've realized that I just don't want to complicate current engine's move generator. However the game itself (jiangqi) seems to be really exciting. Here's the point - despite the fact it's not obvious to be able to play a game in order to create playing engine, still I prefer to master a game at somewhat novice level first. This is what I did before coding xiangqi engine. So to start a jianggi engine I first need to lose around 100 jianggi games as a human player)

Now here's the idea that has just come to my mind - the project you're requesting might be done much faster if we deal on a paid bases (fixed price paid by milestones). You can mail me to freesoft.for.peole@gmail.com for details.

Some benefits you might have in this case:
1. Engine may be implemented in different programming languages with different purposes in mind, for instance:
- in javascript (this would allow to play in browser directly, see playable example: https://maksimkorzh.github.io/wukong-xiangqi/src/gui/xiangqi.html but also within winboard, see how I played my xiangqi engine written in javascript versus maxQi by H.G. Muller, maintainer of Winboard: https://www.youtube.com/watch?v=NmXhAUnKLe0)
- in C/C++ (would be faster and stronger but won't have own UI, however it's possible to make a custom UI like my CCBridge Arena: https://github.com/maksimKorzh/ccbridge-arena)
2. Priority (paid projects are prior to hobby projects, so I can drop what I currently do and start working on jianggi project instantly)
3. Customization & revising  (literally on-demand feature requests/upgrades/support etc.)

Potentially this can be turned into commercial project you might want to start selling one day (but in this case it would be a custom stuff, no longer derived from stockfish to avoid licencing issues)

I would say that this is something I'm interested to discuss in particular.

On the other hand on free bases somewhat similar project might occur in a year or two, but again like I can't promise for sure because my hobby stuff flows on it's own - I mean I do something for free IF that is interesting to me and WHEN it is interesting
for me and not on demand, hope you understand)

**Comment by cjssh1002** [comment]
Thank you for your favors and suggestions.

First of all, as you said, it seems impossible to surpass Fairy Stockfish in the short term, assuming you are developing your current engine.
And now I don't yet need the engine used for web programs.
Finally, in fact, I am currently developing janggi with the Winboard developer.
So, because I have to help the Winboard developer, it seems difficult to ask for another project for a fee or help with testing.

However, even if it is not a janggi engine, if you develop it so that the janggi engine can run in GUI, it will certainly be helpful to Korean users.

And as a result, I and many Korean users can make donations.

**Comment by maksimKorzh** [comment]
re:  it seems impossible to surpass Fairy Stockfish in the short term
 - I'm happy you understand it)
 
re: Finally, in fact, I am currently developing janggi with the Winboard developer
 - you mean with H.G. Muller? Congrats!

re:  ...because I have to help the Winboard developer...
- yeah, for sure it's better to help H.G. Muller especially bearing in mind you're a pro player. I believe this should result in great engine!

re: ...as a result, ... users can make donations
- haha) I though this would be so for xiangqi, but I've gifted fo free all I've developed)))

Today I played a few jiangqi games versus fairy stockfish - this was really fun)
Jiangi has some unique charm no that no other variant have)
I managed to beat random mover but obviously got crushed by any stronger levels)))

To be honest making a playing engine for whatever variant is not really that big deal if you have experience with chess programming, however the tricky thing is to set up proper goals ones you start a project. It's still a big issue for me - 
my original goals are always "simplest possible proof of concept implementation" no matter how complicated project is and this always leads to a working prototype I completely lose interest to after starts initially working. With this current xiangqi stockfish I have the same issue - I already see that I can bring it to somewhat a decent playing strength but unfortunately I can't see much sense in further development for some reason. All I do kind of lives as a youtube show/series and ones it's completed I usually start a new one... I wish I could bring all the stuff I've done so far together into a single product, but it's a complete mystery to me what kind of stuff can lead to a common denominator.

**Comment by maksimKorzh** [comment]
Hi @cjssh1002 
I've made a traditional janggi theme for winboard/xboard:
http://talkchess.com/forum3/viewtopic.php?f=2&t=76959
maybe you get interested.

Also this xiangqi stockfish project is now stopped due to some conflicts I have in my head)))
So I'm now starting to research janggi and hope to come up with another engine, just like you wanted)
I will first port my wukong-xiangqi from JS to C and then alter the movegen to play janggi.
It should be at least as strong as HGM's J 0.2b, btw did you already test that?

P.S. It's such a pleasure to watch engines playing janggi with traditional board and pieces!

**Comment by cjssh1002** [comment]
Hi, Korzh

Thank you very much for your interest in Janggi.
Of course, I am also very interesting in your pieces image and board image.

First of all, it is impossible to run traditional janggi images and boards on a Window10 system the way you do it.
99% of Koreans run Winboard janggi on Windows 7~10 systems.
Now that you are running Winboard on Linux, the board image and the traditional pieces image are displayed normally.
However, I used your board and pieces image on window 10 64bit, but it was not displayed normally. (This problem also has existed before, and I have tried a lot to solve it.)
![캡처](https://user-images.githubusercontent.com/63978900/112712860-61090b80-8f15-11eb-98b5-d7e30de6b091.PNG)

So I personally made 'janggi font' for winboard.
I will send the janggi-font and janggi-board image that I made to your e-mail. Please check your email.~!! (However, please do not share it yet.)
And I will compile and send the latest two versions of Fairy Stockfish.
The stockfish version tested in the current video is version 11.2. The 13 version is more powerful and the latest version. Considering your computer's specifications, we compiled it into two types. In particular, the performance of the largeboard differs depending on the compilation method. And I modified some code.(bmi2/modern)

I haven't tested HGM's J0.2b yet. Perhaps it is similar to J0.2. This is just a simple search engine for reinforcement learning. So it doesn't mean much to the test yet. In fact, it has its weaknesses because it quickly separate the cannon. And pawns advance very quickly.

and I personally makeing the janggi-PST manually.
And I'm making a pattern for Janggi's tactics.

Before, I suggested Fabian Fichter a lot of performance tests and tactics as well as rules for janggi, some of which were adopted, which janggi could lead to a lot of strength gains.

If you will building a janggi engine I would like to test my tactics. ^^;

Regards,
Baek

Ps, Do you know how to properly display your images and boards on Windows 10 systems?

Ps2. I sent a message to your e-mail, but maybe your e-mail ran into trouble.
![캡처2](https://user-images.githubusercontent.com/63978900/112713229-8ac33200-8f17-11eb-8db9-30a4d65ac5c7.PNG)

**Comment by maksimKorzh** [comment]
Hi @cjssh1002 

First of all there's a typo in the email, it should be:
freesoft.for.people@gmail.com  (peoPle, not peole)

re: images on windows 10
 - Some theory first. I use wine (windows environment emulator, windows 10 is emulated in particular) to run winboard. So the issue you're facing is 99% image path issue, not OS issue. I can't guarantee that it would work with your current version of winboard, but the version HGM has sent me should work (download this repo: https://github.com/maksimKorzh/chess_programming see /janggi/WinBoard/WinBoard folder for the exact version of WinBoard, it's configured to run janggi by default).
 - Now regarding images. You need to specify YOUR OWN PATH to images becasue otherwise it would most likely rely on the path specific to my environment. In the video I'm showing how to do that.

Start with board texture, this should be trivial:
1. Open View=>Board Themes...
2. Specify Light-Square texture and Dark-Square texture (pick up "Janggi.bmp" from /theme_winboard folder), click on Use board textures checkbox.

It should display the board texture. If not try a whatever custom ".bmp" file with the same size (width and height in pixels)
this would tell whether the issue in the texture encoding or not.

3. Specify Directory with piece bitmaps as well
![Screenshot from 2021-03-27 12-25-06](https://user-images.githubusercontent.com/34242153/112717960-89ced800-8ef8-11eb-908f-1cdf02d7b047.png)

It SHOULD work, please let me know if it helps.

re: engine related questions
 - all ideas are very exciting, give me a bit of a time, I'll creae a new repo for janggi engine and we'll move this discussion there

Looking forward.

P.S. Email is also fine if you prefer private discussion.

**Comment by maksimKorzh** [comment]
@cjssh1002 
I moved the discussion here: https://github.com/maksimKorzh/wukong-janggi/issues/1
This issue would be closed.
